target-version = "py310"
line-length = 120
exclude = [
  ".git,",
  "__pycache__",
  "build",
  "{{ cookiecutter.package_name }}/version.py",
]

[lint]
select = [
  "E",
  "F",
  "W",
  "UP",
  "PT",
  {%- if cookiecutter.use_extended_ruff_linting == 'y' %}
  "N",
  "BLE",
  "A",
  "C4",
  "INP",
  "PIE",
  "T20",
  "RET",
  "TID",
  "PTH",
  "PD",
  "PLC",
  "PLE",
  "FLY",
  "NPY",
  "PERF",
  "RUF",
  {%- endif %}
]
extend-ignore = [
  # pycodestyle
  "E501", # ignore line length will use a formatter instead
  "E712", # Avoid equality comparisons to True; use if {cond}: for truth checks
  "E721", # type comparison Use is and is not for type comparisons, or isinstance() for isinstance checks
  # upgrades
  "UP038", # Use | in isinstance - not compatible with models and is slower
  # pytest (PT)
  "PT001", # Always use pytest.fixture()
  "PT004", # Fixtures which don't return anything should have leading _
  "PT011",  # except(ValueRaises) is too broad
  "PT023", # Always use () on pytest decorators
  # flake8-pie
  "PIE808", # Disallow passing 0 as the first argument to range
  # flake8-use-pathlib
  "PTH123", # open() should be replaced by Path.open()
  # Ruff
  "RUF003", # Ignore ambiguous quote marks, doesn't allow ' in comments
  "RUF012",  # Mutable class attributes should be annotated with `typing.ClassVar`
  "RUF013",  # PEP 484 prohibits implicit `Optional`
  "RUF015",  # Prefer `next(iter(...))` over single element slice
]

[lint.per-file-ignores]
# Part of configuration, not a package.
"setup.py" = ["INP001"]
"conftest.py" = ["INP001"]
"docs/conf.py" = [
  "E402"  # Module imports not at top of file
]
"docs/*.py" = [
  "INP001",  # Implicit-namespace-package. The examples are not a package.
]
"examples/**.py" = [
  "T201", # allow use of print in examples
]
"__init__.py" = ["E402", "F401", "F403"]
"test_*.py" = ["B011", "D", "E402", "PGH001", "S101"]

[lint.pydocstyle]
convention = "numpy"
